mapping = {
    "01_Titel":"dc:title",
    "02_Bildnummer":"Iptc4xmpCore:SubjectCode",
    "03_Aufnahmedatum":"photoshop:DateCreated",
    "04_Bildautor":" dc:creator",
    "05_Freigabe":"dc:rights",
    "06_Verantwortlichkeit":"photoshop:Source",
    "07_Veraenderbarkeit":"photoshop:Instructions",
    "08_Ortsbezeichnung1":"photoshop:City",
    "09_Ortsbezeichnung2":"Iptc4xmpCore:Location",
    "10_Objekt1":"dc:description",
    "11_Objekt2":"photoshop:SupplementalCategory",
#    "12_Objekt3":"Iptc4xmpCore:LocalCaption",
    "13_Dateityp":"dc:format",
    "Land":"photoshop:Country",
    "Schlagworte":"dc:subject",
    "Institution":"photoshop:CaptionWriter",
    "Bildunterschrift":"photoshop:Headline",
}
